"""Add xba_against, extension, z_swing_rate, stuff_plus, location_plus to pitcher stats

Revision ID: 0e438d7653f3
Revises: dda837c63124
Create Date: 2026-07-15 18:48:09.841050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e438d7653f3'
down_revision: Union[str, Sequence[str], None] = 'dda837c63124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitcher_stats', sa.Column('xba_against', sa.Numeric(precision=5, scale=3), nullable=True))
    op.add_column('pitcher_stats', sa.Column('z_swing_rate', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('pitcher_stats', sa.Column('extension', sa.Numeric(precision=3, scale=1), nullable=True))
    op.add_column('pitcher_stats', sa.Column('stuff_plus', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('pitcher_stats', sa.Column('location_plus', sa.Numeric(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitcher_stats', 'location_plus')
    op.drop_column('pitcher_stats', 'stuff_plus')
    op.drop_column('pitcher_stats', 'extension')
    op.drop_column('pitcher_stats', 'z_swing_rate')
    op.drop_column('pitcher_stats', 'xba_against')
    # ### end Alembic commands ###
