"""add chase_rate and whiff_rate to batter_stats

Revision ID: 5b8d1dbb8fe5
Revises: 55ecc7b8f7e9
Create Date: 2026-07-15 15:09:23.413363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8d1dbb8fe5'
down_revision: Union[str, Sequence[str], None] = '55ecc7b8f7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batter_stats', sa.Column('chase_rate', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('batter_stats', sa.Column('whiff_rate', sa.Numeric(precision=4, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batter_stats', 'whiff_rate')
    op.drop_column('batter_stats', 'chase_rate')
    # ### end Alembic commands ###
