"""add service_time to player_salaries

Revision ID: 69c09c5b025c
Revises: cfcc1243c7ad
Create Date: 2026-08-05 22:48:05.773632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c09c5b025c'
down_revision: Union[str, Sequence[str], None] = 'cfcc1243c7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_salaries', sa.Column('service_time', sa.Numeric(precision=5, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_salaries', 'service_time')
    # ### end Alembic commands ###
