"""add fWAR to batter_stats and pitcher_stats

Revision ID: 7329ac20db67
Revises: 69c09c5b025c
Create Date: 2026-08-05 23:26:50.534781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7329ac20db67'
down_revision: Union[str, Sequence[str], None] = '69c09c5b025c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batter_stats', sa.Column('war', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('pitcher_stats', sa.Column('war', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitcher_stats', 'war')
    op.drop_column('batter_stats', 'war')
    # ### end Alembic commands ###
