"""widen stat percentage columns to avoid overflow

Revision ID: 79bc2eaf3069
Revises: 88cd165faed0
Create Date: 2026-07-07 16:24:22.418925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bc2eaf3069'
down_revision: Union[str, Sequence[str], None] = '88cd165faed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batter_stats', 'ba',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'obp',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'slg',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'ops',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'xba',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'xslg',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'xwoba',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'woba',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'barrel_rate',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('batter_stats', 'hard_hit_rate',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'era',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'whip',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'fip',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'k_9',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'bb_9',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'xera',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'xwoba_against',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'hard_hit_rate_against',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'barrel_rate_against',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitcher_stats', 'barrel_rate_against',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'hard_hit_rate_against',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'xwoba_against',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'xera',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'bb_9',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'k_9',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'fip',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'whip',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('pitcher_stats', 'era',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('batter_stats', 'hard_hit_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'barrel_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'woba',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'xwoba',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'xslg',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'xba',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'ops',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'slg',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'obp',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('batter_stats', 'ba',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###
