"""initial schema

Revision ID: 88cd165faed0
Revises: 
Create Date: 2026-07-07 12:50:15.525539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88cd165faed0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('bats', sa.String(length=1), nullable=True),
    sa.Column('throws', sa.String(length=1), nullable=True),
    sa.Column('debut_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.SmallInteger(), nullable=False),
    sa.Column('abbreviation', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('league', sa.Enum('AL', 'NL', name='league_enum'), nullable=False),
    sa.Column('division', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('abbreviation')
    )
    op.create_table('batter_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('team_id', sa.SmallInteger(), nullable=False),
    sa.Column('pa', sa.Integer(), nullable=True),
    sa.Column('ba', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('obp', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('slg', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ops', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('xba', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('xslg', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('xwoba', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('woba', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('hr', sa.SmallInteger(), nullable=True),
    sa.Column('rbi', sa.SmallInteger(), nullable=True),
    sa.Column('sb', sa.SmallInteger(), nullable=True),
    sa.Column('barrel_rate', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('hard_hit_rate', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('avg_exit_velo', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('sprint_speed', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('k_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('bb_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season')
    )
    op.create_table('pitcher_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('team_id', sa.SmallInteger(), nullable=False),
    sa.Column('ip', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('era', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('whip', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('fip', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('k_9', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('bb_9', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('xera', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('xwoba_against', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('hard_hit_rate_against', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('barrel_rate_against', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('avg_exit_velo_against', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season')
    )
    op.create_table('player_salaries',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('team_id', sa.SmallInteger(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('aav', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contract_years_total', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season')
    )
    op.create_table('player_seasons',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('player_type', sa.Enum('BATTER', 'PITCHER', name='player_type_enum'), nullable=False),
    sa.Column('team_id', sa.SmallInteger(), nullable=False),
    sa.Column('position', sa.Enum('C', 'FIRST_BASE', 'SECOND_BASE', 'THIRD_BASE', 'SS', 'LF', 'CF', 'RF', 'DH', 'SP', 'RP', name='position_enum'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season', 'player_type')
    )
    op.create_table('player_value',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('position', sa.Enum('C', 'FIRST_BASE', 'SECOND_BASE', 'THIRD_BASE', 'SS', 'LF', 'CF', 'RF', 'DH', 'SP', 'RP', name='position_enum'), nullable=False),
    sa.Column('composite_percentile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('salary_percentile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('value_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season')
    )
    op.create_table('team_payroll_summary',
    sa.Column('team_id', sa.SmallInteger(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('total_payroll', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('avg_value_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('team_id', 'season')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_payroll_summary')
    op.drop_table('player_value')
    op.drop_table('player_seasons')
    op.drop_table('player_salaries')
    op.drop_table('pitcher_stats')
    op.drop_table('batter_stats')
    op.drop_table('teams')
    op.drop_table('players')
    # ### end Alembic commands ###
