"""add wrc_plus to batter_stats

Revision ID: b90b16934eee
Revises: 8d995c8678d3
Create Date: 2026-08-18 13:17:18.420724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90b16934eee'
down_revision: Union[str, Sequence[str], None] = '8d995c8678d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batter_stats', sa.Column('wrc_plus', sa.Numeric(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batter_stats', 'wrc_plus')
    # ### end Alembic commands ###
