"""add traditional counting stats

Revision ID: cfcc1243c7ad
Revises: 0e438d7653f3
Create Date: 2026-08-05 14:51:49.414948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfcc1243c7ad'
down_revision: Union[str, Sequence[str], None] = '0e438d7653f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batter_stats', sa.Column('hits', sa.SmallInteger(), nullable=True))
    op.add_column('batter_stats', sa.Column('games', sa.SmallInteger(), nullable=True))
    op.add_column('pitcher_stats', sa.Column('wins', sa.SmallInteger(), nullable=True))
    op.add_column('pitcher_stats', sa.Column('saves', sa.SmallInteger(), nullable=True))
    op.add_column('pitcher_stats', sa.Column('games_started', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitcher_stats', 'games_started')
    op.drop_column('pitcher_stats', 'saves')
    op.drop_column('pitcher_stats', 'wins')
    op.drop_column('batter_stats', 'games')
    op.drop_column('batter_stats', 'hits')
    # ### end Alembic commands ###
