"""add contract_type and projected_salary for pre-arb handling

Revision ID: dae653a224c0
Revises: d77ee9e7a03c
Create Date: 2026-07-07 19:22:59.606760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae653a224c0'
down_revision: Union[str, Sequence[str], None] = 'd77ee9e7a03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_salaries', sa.Column('contract_type', sa.String(length=20), nullable=True))
    op.add_column('player_value', sa.Column('projected_salary', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_value', 'projected_salary')
    op.drop_column('player_salaries', 'contract_type')
    # ### end Alembic commands ###
