"""add k_rate, bb_rate, chase_rate, whiff_rate to pitcher_stats

Revision ID: dda837c63124
Revises: 5b8d1dbb8fe5
Create Date: 2026-07-15 15:30:20.727863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda837c63124'
down_revision: Union[str, Sequence[str], None] = '5b8d1dbb8fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitcher_stats', sa.Column('k_rate', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('pitcher_stats', sa.Column('bb_rate', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('pitcher_stats', sa.Column('chase_rate', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('pitcher_stats', sa.Column('whiff_rate', sa.Numeric(precision=4, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitcher_stats', 'whiff_rate')
    op.drop_column('pitcher_stats', 'chase_rate')
    op.drop_column('pitcher_stats', 'bb_rate')
    op.drop_column('pitcher_stats', 'k_rate')
    # ### end Alembic commands ###
