"""add fielding_stats table

Revision ID: ef313b50121e
Revises: 79bc2eaf3069
Create Date: 2026-07-07 16:35:22.833856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef313b50121e'
down_revision: Union[str, Sequence[str], None] = '79bc2eaf3069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fielding_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('team_id', sa.SmallInteger(), nullable=False),
    sa.Column('innings', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('oaa', sa.SmallInteger(), nullable=True),
    sa.Column('frv', sa.SmallInteger(), nullable=True),
    sa.Column('drs', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fielding_stats')
    # ### end Alembic commands ###
