"""add arb_outcomes table

Revision ID: fd884542ff3e
Revises: 7329ac20db67
Create Date: 2026-08-06 11:46:02.327678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd884542ff3e'
down_revision: Union[str, Sequence[str], None] = '7329ac20db67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arb_outcomes',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('platform_season', sa.SmallInteger(), nullable=False),
    sa.Column('service_time', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('actual_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'platform_season')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arb_outcomes')
    # ### end Alembic commands ###
